[package]
name = "stm32f3-leds-with-registers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt = "0.6.13"
panic-itm = "0.4.2"
stm32f3-discovery = "0.6.0"
cortex-m = "0.6.4"
